# This is a basic workflow to help you get started with Actions

name: coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install -r requirements.txt

      - name: Analysing the code with pylint
        run: |
          coverage run -m src.server >& $SERVER_LOG &
          pylint tests/
          pytest 
          kill -SIGINT %1
          cat $SERVER_LOG
          coverage report
          coverage html
